development:
  adapter: postgresql
  encoding: unicode
  database: dans_the_man_development
  pool: 5
  username: jschmitz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dans_the_man_test
  pool: 5
  username: postgres
  password:
